### ISSUE TITLE
Integration with ASP.Net WebForms app

### ISSUE THREAD

**Issue by Whatty** [microsoftgraph/aspnet-connect-sample#12]
I am trying to integrate the example into an existing ASP.Net WebPages.

The example APP works fine, however, when I try and integrate it into my application I can't get the API controller method to get called and based on my debugging so far the routes are null. I am fairly positive it is because the ASP handler / modules are interfering with the MVC controller handlers / modules but can't figure out how to effectively debug this - it is not a routing problem per se, but the fact that the routes are null

Any hints on how to trouble-shoot this or does anyone have a working example that includes integration with aspx pages based application.

Thanks in advance.

Whatty

**Comment by DianeD** [comment]
Hi @Whatty . Sorry, I'm not aware of any examples. 

We did find a couple of resources about the reverse process that may help shed light on converting in the other direction:

- https://msdn.microsoft.com/en-us/magazine/jj991978.aspx
- http://stackoverflow.com/questions/211744/best-way-to-gradually-convert-an-existing-asp-net-site-to-mvc

You might try asking on [Stack Overflow](https://stackoverflow.com/). If any part of your issue seems related to the Microsoft Graph API, please tag the question with [MicrosoftGraph].

**Comment by Whatty** [comment]
My app uses ExtJS from Sencha to build the pages, so my pages are nothing more than simple containers in which to render the JS. Thus I have determined that it is time for port forward instead of supporting the older aspx pages - I may regret this but conceptually it should be straight-forward.
