### ISSUE TITLE
Integration with an on-prem Exchange with EWS

### ISSUE THREAD

**Issue by Whatty** [microsoftgraph/aspnet-connect-sample#21]
Are there any examples on how to integrate this with an on-prem Exchange installation with EWS 

My assumption, which may be correct, that this should also support that model.

**Comment by jamescro** [comment]
I don't believe that this sample, or any of the samples that use the MSAL library (with the v2.0 Azure AD endpoint), can work with an on-prem Exchange setup. The tokens you get back will work only with Office 365.

**Comment by Whatty** [comment]
If I get the authentication piece work - the actual calls should be compatible though - correct?

**Comment by jamescro** [comment]
I think so. But you can't be sure that the metadata on your on-prem installation is up-to-date and consistent with what's on O365, so the SDK calls might not always work.

**Comment by Whatty** [comment]
Does that not contradict one of the fundamental design objectives of EWS - making the calls intra-operable between on-prem / cloud - and the fact that the Graph API does not take this into account is I have to admit somewhat disappointing.

As an ISV when I saw that the stated direction of EWS was this level of intra-operability I was impressed and glad that I would not have to figure out how to support the two models independently. Understandably this is going to be difficult to support, since I am assuming the online Graph API / service will evolve quicker and easier than that of a on-prem installed EWS, but imagine the pain an ISV is going to go through to support this much needed aspect

**Comment by jasonjoh** [comment]
Hey @Whatty, thanks for the question! EWS does work across on-premises and Office 365 as far as the specific SOAP operations and request/response formats. No issues there. The problem you're most likely going to run into is the auth piece as used in this sample.

EWS itself was brought into being before OAuth was a thing, so it was designed more to use Basic, NTLM, or cert-based auth. Most apps out there use Basic since that's the easiest and Office 365 supports it.

Graph on the other hand, requires OAuth. This samples shows how to use MSAL to authorize the app using an Azure AD account. Office 365 Exchange servers know how to handle these kinds of tokens, and you can actually get a token that will work with EWS against Office 365 servers this way.

My understanding for on-premises Exchange is that in order for them to understand the types of tokens used in this sample, it requires a lot of configuration, including the installation of servers that can issue the OAuth tokens needed. Typically for on-premises the easiest solution is to continue to use Basic or NTLM.

However none of this should impact the actual EWS operations, just how you authenticate.

As for Graph: long term we would like to make this available to on-premises, at least in some fashion. We've taken some steps in that direction, enabling the Outlook APIs in hybrid setups (https://channel9.msdn.com/Events/Ignite/2016/BRK3045), but we're not there yet.

**Comment by Whatty** [comment]
Jason - thanks for the reply and I am glad to see the stated direction is for this level of intra-operability. Understandably with the cadence of releases / versions for on-prem versus cloud platform in which the EWS calls operate, this is a very challenging position to be in.

In the short-term - I am trying to determine my path forward for the on-prem calls and seeing just how much I have to modified the existing Graph SDK to work with Basic or NTLM model. It may mean I will be maintaining a bifurcated implementation (Graph based or other) in the short-term, but we have already seen requests from our clients to support the OAuth2 model for internal deployments of Exchange, which will bring me back to single pattern

**Comment by jasonjoh** [comment]
To be clear, Graph doesn't work on premises. I'm not sure what you could do to modify the SDK short of trying to replicate the actions with EWS operations.
